name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  lint-branch:
    name: Lint Branch Name
    runs-on: ubuntu-latest
    steps:
      - name: Validate branch name
        env:
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
          BRANCH_PATTERN: '(major|minor|patch|dependabot)\/.*'
        run: echo "${BRANCH_NAME}" | grep -E "${BRANCH_PATTERN}"

  lint-code:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install Dependencies
        run: npm ci
      - name: Lint Project
        run: npm run lint

  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
